import express from "express";
import { requireAuth } from "../middleware/auth.js";

const router = express.Router();

router.post("/generate", requireAuth, async (req, res, next) => {
  try {
    const { prompt, tone = "Professional", type = "custom", brandName = "MailBridge" } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required." });
    }

    const geminiKey = process.env.GEMINI_API_KEY;

    if (geminiKey) {
      // call Gemini API using native fetch
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`;
      
      const promptText = `
You are an expert AI copywriter for transactional and marketing emails.
Write a compelling email subject line and message body based on this prompt.

Input Parameters:
- Brand Name: ${brandName}
- Email Type/Context: ${type}
- Target Tone: ${tone} (e.g. Professional, Friendly, Casual, Urgent, Persuasive)
- Description of what the email should say: ${prompt}

Output format:
Provide your output as a valid JSON object matching this schema exactly:
{
  "subject": "The email subject line",
  "message": "The email message body. Use newlines (\\n) for spacing where appropriate. Do NOT write HTML."
}

Do NOT wrap the JSON in markdown code blocks or triple backticks. Return ONLY the raw JSON text.
      `.trim();

      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: promptText
                }
              ]
            }
          ],
          generationConfig: {
            responseMimeType: "application/json"
          }
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${errorText}`);
      }

      const data = await response.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error("No content generated by Gemini.");
      }

      try {
        const parsed = JSON.parse(text.trim());
        return res.json({
          success: true,
          subject: parsed.subject || `Update from ${brandName}`,
          message: parsed.message || prompt,
          isMock: false
        });
      } catch (err) {
        console.error("Failed to parse Gemini JSON:", text, err);
        // Fallback to text parsing if JSON is not valid
        return res.json({
          success: true,
          subject: `Update from ${brandName}`,
          message: text.trim(),
          isMock: false
        });
      }
    } else {
      // Fallback/Mock generator for when GEMINI_API_KEY is not defined
      let subject = "";
      let message = "";

      const lowerPrompt = prompt.toLowerCase();
      const brand = brandName || "MailBridge";

      // Formulate a very high-quality email template response based on tone and prompt
      if (type === "welcome" || lowerPrompt.includes("welcome") || lowerPrompt.includes("signup") || lowerPrompt.includes("sign up")) {
        subject = tone === "Friendly" ? `Welcome to the ${brand} family! ✨` 
                : tone === "Urgent" ? `Confirm your new account at ${brand} now`
                : tone === "Persuasive" ? `You've made the right choice! Welcome to ${brand}`
                : `Welcome to ${brand} - Let's get started`;
        
        message = `Hi there,\n\nWelcome to ${brand}! We're thrilled to have you join us.\n\nYour account has been set up successfully. Based on your details ("${prompt}"), we want to make sure you get the most out of your experience.\n\nIf you have any questions or need help, just reply to this email. Our support team is always here for you.\n\nBest regards,\nThe ${brand} Team`;
      } else if (type === "forgot-password" || lowerPrompt.includes("reset") || lowerPrompt.includes("password")) {
        subject = tone === "Urgent" ? `Action Required: Reset your ${brand} password`
                : `Reset your ${brand} account password`;
        
        message = `Hello,\n\nWe received a request to reset the password for your ${brand} account.\n\nTo reset your password, please use the button below or follow the link provided in your app. If you didn't request this, you can safely ignore this email.\n\nThis password reset link will expire in 2 hours for security reasons.\n\nBest regards,\n${brand} Security Team`;
      } else if (type === "otp" || lowerPrompt.includes("code") || lowerPrompt.includes("verification") || lowerPrompt.includes("otp")) {
        subject = tone === "Urgent" ? `URGENT: Your ${brand} Verification Code`
                : `Your ${brand} security code`;
        
        message = `Hello,\n\nYour security verification code for ${brand} is below. Please enter this code to verify your identity.\n\nVerification Code: 482931\n\nThis code will expire in 10 minutes. If you did not make this request, please contact support immediately.\n\nBest regards,\n${brand} Team`;
      } else if (type === "notification" || lowerPrompt.includes("alert") || lowerPrompt.includes("notify") || lowerPrompt.includes("maintenance")) {
        subject = tone === "Urgent" ? `IMPORTANT: Update regarding your ${brand} service`
                : tone === "Friendly" ? `Quick heads-up from ${brand}`
                : `Notification from ${brand}`;
        
        message = `Hello,\n\nThis is an automated notification from ${brand} regarding your account or services.\n\nSummary of update:\n${prompt}\n\nNo immediate action is required unless specified otherwise. We appreciate your partnership with us.\n\nBest regards,\nThe ${brand} Team`;
      } else {
        // Custom marketing or other email
        subject = tone === "Friendly" ? `A quick message from ${brand} ✨`
                : tone === "Urgent" ? `Important update: ${prompt.substring(0, 40)}...`
                : tone === "Persuasive" ? `Why you don't want to miss this from ${brand}`
                : `Update from ${brand}`;
        
        message = `Hi there,\n\nWe wanted to reach out to you with an update from ${brand}.\n\nHere is what's new:\n${prompt}\n\nWe hope this information is helpful to you. Please let us know if you have any questions or feedback!\n\nBest regards,\nThe ${brand} Team`;
      }

      return res.json({
        success: true,
        subject,
        message,
        isMock: true,
        note: "Using mock AI. Please configure GEMINI_API_KEY in your .env file to enable live Gemini AI generation."
      });
    }
  } catch (error) {
    next(error);
  }
});

export default router;
